# Generated by Django 4.2.5 on 2023-09-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('image', models.URLField(verbose_name='Ссылка на фото')),
                ('release_date', models.DateField(verbose_name='Дата начала продаж')),
                ('lte_exists', models.BooleanField(default=False, verbose_name='Функция LTE')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name=models.CharField(max_length=255, unique=True, verbose_name='Название'))),
            ],
        ),
    ]
